/**
 * OphthaMCQ Marketing Site Configuration
 *
 * This .net site serves as the marketing/content/SEO frontend.
 * All checkout, login, signup, and product purchase flows redirect to .com
 */

export const SITE = {
  name: 'OphthaMCQ',
  tagline: 'The Only Ophthalmology Question Bank Built by Doctors Who Passed These Exams',
  description:
    '10,000+ MCQs, Handwritten Notes, Past Papers with Explanations. For FRCOphth, ICO, FAICO, DNB & NEET-SS.',
  // Marketing site on .org (apex is canonical; www redirects here in production).
  // Checkout/auth still live on .com via COM_BASE — do not use .com as page canonicals.
  url: 'https://ophthamcq.org',

  logo: '/logo.svg',
  favicon: '/favicon.svg',
};

/** E-commerce platform on .com — all purchase/auth flows go here */
export const COM_BASE = 'https://www.ophthamcq.com';

/** Real products from the current ophthamcq.com website
 *  Each `href` points to the live product page on .com so users
 *  land on the correct product to purchase. */
export const PRODUCTS = [
  {
    id: 'retina-deciphered',
    name: 'Retina Deciphered',
    fullName: 'Retina Deciphered: Exam Ready Handwritten Notes for Ophthalmology',
    price: '₹549',
    oldPrice: '₹899',
    discount: '39%',
    description: '150+ pages of handwritten exam-ready notes covering the entire retina syllabus.',
    href: `${COM_BASE}/new-courses/3-retina-deciphered-exam-ready-handwritten-notes-for-ophthalmology`,
    image: '/product-images/retina-deciphered.webp',
    imageWidth: 900,
    imageHeight: 1164,
    icon: 'notes',
    tag: 'Most Popular',
    category: 'notes',
  },
  {
    id: 'ico-fico-past-papers',
    name: 'ICO/FICO Past Papers',
    fullName: 'ICO/FICO Past Papers with Full Explanations',
    price: '₹1,799',
    oldPrice: '₹3,000',
    discount: '41%',
    description: 'Last 10 years of ICO/FICO past papers with full explanations and answer keys.',
    href: `${COM_BASE}/new-courses/23-ico-fico-past-papers`,
    image: '/product-images/ico-fico-past-papers.webp',
    imageWidth: 447,
    imageHeight: 447,
    icon: 'pastPapers',
    tag: 'Best Value',
    category: 'past-papers',
  },
  {
    id: 'high-yield-mcqs',
    name: 'High Yield MCQs',
    fullName: 'Ophthalmology MCQs High Yield',
    price: '₹399',
    oldPrice: '₹899',
    discount: '56%',
    description: '1,000+ high-yield MCQs across all subspecialties with detailed explanations.',
    href: `${COM_BASE}/new-courses/25-ophthalmology-mcqs-high-yield`,
    image: '/product-images/high-yield-mcqs.webp',
    imageWidth: 900,
    imageHeight: 600,
    icon: 'mcq',
    tag: 'Essential',
    category: 'mcqs',
  },
  {
    id: 'faico-mcqs',
    name: 'FAICO MCQs',
    fullName: 'FAICO MCQs — AIOS Fellowship Exam Preparation',
    price: '₹929',
    oldPrice: '₹1,500',
    discount: '39%',
    description: 'FAICO exam MCQs mapped topic-by-topic to the exact syllabus.',
    href: `${COM_BASE}/new-courses/14-faico-mcqs`,
    image: '/product-images/faico-mcqs.webp',
    imageWidth: 500,
    imageHeight: 350,
    icon: 'questionBank',
    tag: 'Syllabus-Mapped',
    category: 'mcqs',
  },
  {
    id: 'eyelids-notes',
    name: 'Eyelids Exam Ready Notes',
    fullName: 'Eyelids Exam Ready Handwritten Notes for Ophthalmology Residents and Postgraduates',
    price: '₹249',
    oldPrice: '₹429',
    discount: '42%',
    description: 'Oculoplastics and eyelid disorders for your PG and fellowship exams.',
    href: `${COM_BASE}/new-courses/31-eyelids-exam-ready-handwritten-notes-for-ophthalmology-residents-and-postgraduates`,
    image: '/product-images/eyelids-notes.webp',
    imageWidth: 900,
    imageHeight: 1164,
    icon: 'notes',
    tag: null,
    category: 'notes',
  },
  {
    id: 'anatomy-notes',
    name: 'Anatomy of Eye Notes',
    fullName: 'Anatomy of Eye & Related Ocular Structures Exam Ready Handwritten Notes',
    price: '₹360',
    oldPrice: '₹500',
    discount: '29%',
    description: 'Complete ocular anatomy with clinical correlations and exam focus.',
    href: `${COM_BASE}/new-courses/4-anatomy-of-eye-related-ocular-structures-exam-ready-handwritten-notes`,
    image: '/product-images/anatomy-notes.webp',
    imageWidth: 900,
    imageHeight: 1436,
    icon: 'notes',
    tag: null,
    category: 'notes',
  },
  {
    id: 'glaucoma-notes',
    name: 'Glaucoma Exam Ready Notes',
    fullName: 'Glaucoma Exam Ready Handwritten Notes',
    price: '₹369',
    oldPrice: '₹699',
    discount: '48%',
    description: 'Complete glaucoma notes from pathophysiology to surgical management.',
    href: `${COM_BASE}/new-courses/15-glaucoma-exam-ready-handwritten-notes`,
    image: '/product-images/glaucoma-notes.webp',
    imageWidth: 900,
    imageHeight: 1272,
    icon: 'notes',
    tag: null,
    category: 'notes',
  },
  {
    id: 'optics-notes',
    name: 'Optics & Refraction Notes',
    fullName: 'Optics and Refraction Exam Ready Notes',
    price: '₹999',
    oldPrice: null,
    discount: null,
    description: 'The most feared topic — made simple with diagrams and solved problems.',
    href: `${COM_BASE}/new-courses/7-optics-and-refraction-exam-ready-notes`,
    image: '/product-images/optics-notes.webp',
    imageWidth: 900,
    imageHeight: 1436,
    icon: 'notes',
    tag: 'Premium',
    category: 'notes',
  },
  {
    id: 'ico-basic-visual-sciences',
    name: 'ICO Basic Visual Sciences MCQs',
    fullName: 'ICO Basic Visual Sciences MCQs',
    price: '₹899',
    oldPrice: '₹999',
    discount: '11%',
    description: 'Basic sciences MCQs for ICO Part A preparation.',
    href: `${COM_BASE}/new-courses/26-ico-basic-visual-sciences-mcqs`,
    image: '/product-images/ico-basic-visual-sciences.webp',
    imageWidth: 900,
    imageHeight: 1274,
    icon: 'mcq',
    tag: null,
    category: 'mcqs',
  },
  {
    id: 'pdcet-mcqs',
    name: 'PDCET MCQs',
    fullName: 'PDCET Ophthalmology MCQs',
    price: '₹899',
    oldPrice: null,
    discount: null,
    description: 'High-yield MCQ bank built specifically for the PDCET Ophthalmology exam.',
    href: `${COM_BASE}/new-courses/20-pdcet-mcqs`,
    image: '/product-images/pdcet-mcqs.webp',
    imageWidth: 610,
    imageHeight: 219,
    icon: 'mcq',
    tag: 'New',
    category: 'mcqs',
  },
  {
    id: 'ico-optics-refraction-mcqs-part-a',
    name: 'ICO Optics & Refraction MCQs Part A',
    fullName: 'ICO Optics & Refraction MCQs Part A — ICO/FICO Ophthalmology',
    price: '₹799',
    oldPrice: '₹999',
    discount: '20%',
    description: 'Part A optics and refraction MCQs for ICO/FICO preparation with full explanations.',
    href: `${COM_BASE}/new-courses/32-ico-optics-refraction-mcqs-part-a-ico-fico-ophthalmology`,
    image: '/product-images/ico-optics-refraction-mcqs-part-a.webp',
    imageWidth: 900,
    imageHeight: 1436,
    icon: 'mcq',
    tag: 'Part A',
    category: 'mcqs',
  },
  {
    id: 'frcophth-step-1-mcqs',
    name: 'FRCOphth Step 1 MCQs',
    fullName: 'FRCOphth Step 1 MCQs',
    price: '₹1,499',
    oldPrice: '₹2,000',
    discount: '25%',
    description: 'Comprehensive FRCOphth Part 1 / Step 1 MCQ bank with detailed explanations and exam tips.',
    href: `${COM_BASE}/new-courses/34-frcophth-step-1-mcqs`,
    image: '/product-images/frcophth-step-1-mcqs.webp',
    imageWidth: 900,
    imageHeight: 1274,
    icon: 'mcq',
    tag: 'FRCOphth',
    category: 'mcqs',
  },
  {
    id: 'short-term-phaco',
    name: 'Short-Term Phaco',
    fullName: 'Short-Term Phaco — Ophthalmology Fellowship Preparation',
    price: '₹1,999',
    oldPrice: '₹2,500',
    discount: '20%',
    description: 'Hands-on phacoemulsification fellowship preparation notes and case discussions.',
    href: `${COM_BASE}/new-courses/30-short-term-phaco`,
    image: '/product-images/short-term-phaco.webp',
    imageWidth: 900,
    imageHeight: 1272,
    icon: 'notes',
    tag: 'Fellowship',
    category: 'notes',
  },
  {
    id: 'dnb-do-past-5-year-papers',
    name: 'Past 5-Year Question Papers DNB/DO',
    fullName: 'Past 5-Year Question Papers DNB/DO Ophthal Exam Ready PG Notes',
    price: '₹349',
    oldPrice: '₹499',
    discount: '30%',
    description: 'Last 5 years of DNB/DO ophthalmology question papers with model answers and exam focus.',
    href: `${COM_BASE}/new-courses/8-past-5-year-question-papers-dnb-do-ophthal-exam-ready-pg-notes`,
    image: '/product-images/dnb-do-past-5-year-papers.webp',
    imageWidth: 447,
    imageHeight: 447,
    icon: 'pastPapers',
    tag: 'Past Papers',
    category: 'past-papers',
  },
  {
    id: 'instruments-in-ophthalmology-notes',
    name: 'Instruments in Ophthalmology',
    fullName: 'Instruments in Ophthalmology — Ophthal Exam Ready PG Notes',
    price: '₹299',
    oldPrice: '₹399',
    discount: '25%',
    description: 'High-yield ophthalmic instruments with uses, parts, and viva-ready explanations.',
    href: `${COM_BASE}/new-courses/28-instruments-in-ophthalmology-ophthal-exam-ready-pg-notes`,
    image: '/product-images/instruments-in-ophthalmology-notes.webp',
    imageWidth: 900,
    imageHeight: 1436,
    icon: 'notes',
    tag: null,
    category: 'notes',
  },
  {
    id: 'recent-advances-ophthalmology-notes',
    name: 'Recent Advances in Ophthalmology',
    fullName: 'Recent Advances in Ophthalmology — Ophthal Exam Ready PG Notes',
    price: '₹399',
    oldPrice: '₹549',
    discount: '27%',
    description: 'Latest advances in ophthalmology distilled for PG exams, viva, and interviews.',
    href: `${COM_BASE}/new-courses/22-recent-advances-in-ophthalmology-ophthal-exam-ready-pg-notes`,
    image: '/product-images/recent-advances-ophthalmology-notes.webp',
    imageWidth: 900,
    imageHeight: 600,
    icon: 'notes',
    tag: null,
    category: 'notes',
  },
  {
    id: 'case-presentation-format-notes',
    name: 'Ophthalmology Case Presentation Format',
    fullName: 'Ophthalmology Case Presentation Format — Ophthal Exam Ready PG Notes',
    price: '₹249',
    oldPrice: '₹349',
    discount: '29%',
    description: 'Step-by-step case presentation formats for clinical exams, long cases, and viva.',
    href: `${COM_BASE}/new-courses/13-ophthalmology-case-presentation-format-ophthal-exam-ready-pg-notes`,
    image: '/product-images/case-presentation-format-notes.webp',
    imageWidth: 900,
    imageHeight: 1164,
    icon: 'document',
    tag: null,
    category: 'notes',
  },
  {
    id: 'ophthalmology-drugs-practical-pdf',
    name: 'Ophthalmology Drugs Practical PDF',
    fullName: 'Ophthalmology Drugs Practical PDF — Ophthal Exam Ready PG Notes',
    price: '₹299',
    oldPrice: '₹399',
    discount: '25%',
    description: 'Practical ophthalmology drugs guide with doses, indications, and exam pearls.',
    href: `${COM_BASE}/new-courses/29-ophthalmology-drugs-practical-pdf-ophthal-exam-ready-pg-notes`,
    image: '/product-images/ophthalmology-drugs-practical-pdf.webp',
    imageWidth: 900,
    imageHeight: 1272,
    icon: 'notes',
    tag: null,
    category: 'notes',
  },
  {
    id: 'read-ophthalmology-reports-tests',
    name: 'How to Read Ophthalmology Reports/Tests',
    fullName: 'How to Read Ophthalmology Reports/Tests — Ophthal Exam Ready PG Notes',
    price: '₹349',
    oldPrice: '₹499',
    discount: '30%',
    description: 'Learn to interpret OCT, visual fields, FA, ICGA, B-scan, and other reports like an examiner.',
    href: `${COM_BASE}/new-courses/12-how-to-read-ophthalmology-reports-tests-ophthal-exam-ready-pg-notes`,
    image: '/product-images/read-ophthalmology-reports-tests.webp',
    imageWidth: 900,
    imageHeight: 1164,
    icon: 'document',
    tag: null,
    category: 'notes',
  },
  {
    id: 'rings-dots-lines-spots-guide',
    name: 'Rings, Dots, Lines, Spots in Ophthalmology',
    fullName: 'Rings, Dots, Lines, Spots in Ophthalmology — The Ultimate Clinical Guide',
    price: '₹449',
    oldPrice: '₹599',
    discount: '25%',
    description: 'The ultimate clinical guide to rings, dots, lines, and spots in ophthalmology.',
    href: `${COM_BASE}/new-courses/33-rings-dots-lines-spots-in-ophthalmology-the-ultimate-clinical-guide-ophthal-exam-ready-pg-notes`,
    image: '/product-images/rings-dots-lines-spots-guide.webp',
    imageWidth: 900,
    imageHeight: 600,
    icon: 'bookOpen',
    tag: null,
    category: 'notes',
  },
  {
    id: 'instruments-drugs-practical-viva',
    name: 'Instruments & Drugs for Practical Exams/Viva',
    fullName: 'Ophthalmology Instruments and Drugs for Practical Exams and Viva — Ophthal Exam Ready PG Notes',
    price: '₹399',
    oldPrice: '₹549',
    discount: '27%',
    description: 'Combined instruments and drugs notes for practical exams and viva preparation.',
    href: `${COM_BASE}/new-courses/24-ophthalmology-instruments-and-drugs-for-practical-exams-and-viva-ophthal-exam-ready-pg-notes`,
    image: '/product-images/instruments-drugs-practical-viva.webp',
    imageWidth: 900,
    imageHeight: 1164,
    icon: 'notes',
    tag: null,
    category: 'notes',
  },
] as const;

/** Auth & checkout redirects */
export const CHECKOUT = {
  purchases: `${COM_BASE}/purchases?type=10`,
  settings:  `${COM_BASE}/settings`,
  login:     `${COM_BASE}/login`,
  signup:    `${COM_BASE}/signup`,
} as const;

/** App store links */
export const APP_LINKS = {
  googlePlay: 'https://play.google.com/store/apps/details?id=com.bktxsx.ucjcrq',
  appStore:   'https://apps.apple.com/in/app/ophtha-mcq-faico-ico-pdcet-frc/id6759045904',
} as const;

/** Exams we cover — icon references custom Icon component names */
export const EXAMS = [
  { name: 'ICO / FICO',     full: 'ICO / FICO Exams',                  slug: 'ico-fico',    iconName: 'globe',       description: 'International Council of Ophthalmology' },
  { name: 'FAICO',          full: 'FAICO Exam',                        slug: 'faico',       iconName: 'badgeCheck',  description: 'Fellowship of All India Ophthalmological Society' },
  { name: 'DNB / MS / DO',  full: 'DNB / MS / DO Ophthalmology',       slug: 'dnb',         iconName: 'building',    description: 'Diplomate of National Board' },
  { name: 'PDCET',          full: 'PD-CET Ophthalmology',              slug: 'pd-cet',      iconName: 'target',      description: 'Post Diploma Centralized Entrance Test' },
  { name: 'FRCOphth',       full: 'FRCOphth Exam',                     slug: 'frcophth',    iconName: 'graduationCap', description: 'Royal College of Ophthalmologists', comingSoon: true },
  { name: 'NEET-SS',        full: 'NEET-SS Ophthalmology',              slug: 'neet-ss',     iconName: 'target',      description: 'Superspecialty entrance for MS/DNB graduates' },
  { name: 'OKAPs',          full: 'OKAP Examination',                  slug: 'okaps',       iconName: 'globe',       description: 'Ophthalmic Knowledge Assessment Program (US)' },
  { name: 'Fellowship',     full: 'Ophthalmology Subspecialty Fellowship', slug: 'fellowship', iconName: 'sparkles', description: 'Ophthalmology Subspecialty Fellowship' },
];

/** Nav links */
export const NAV = [
  { label: 'Exams',      href: '/exams/',       external: false },
  { label: 'Free MCQs',  href: '/free-mcqs/',   external: false },
  { label: 'Notes',      href: '/notes/',       external: false },
  { label: 'Topics',     href: '/topics/',      external: false },
  { label: 'Resources',  href: '/resources/',   external: false },
  { label: 'Blog',       href: '/blog/',        external: false },
  { label: 'Glossary',   href: '/glossary/',    external: false },
  { label: 'FAQ',        href: '/faq/',         external: false },
];

/** Testimonials */
export const TESTIMONIALS = [
  { name: 'Dr. Sangam Rout', role: 'DNB Ophthalmology, AIIMS', text: 'The quality of explanations is super so so good. Cleared my DNB theory in first attempt.', exam: 'DNB' },
  { name: 'Dr. Garvesh Surya', role: 'MS Ophthalmology', text: 'The exam ready notes have my heart — extremely helpful for my DNB finals.', exam: 'MS' },
  { name: 'Dr. Umer Shaikh', role: 'FRCOphth, Moorfields Eye Hospital UK', text: 'The best distillation of Ryan, Kanski and Elkington you will ever find. Passed FRCOphth Part 1 with 72%.', exam: 'FRCOphth' },
  { name: 'Dr. Ahmed Khan', role: 'ICO Basic Sciences', text: 'ICO past papers with full explanations were my single biggest advantage. Scored 85%.', exam: 'ICO/FICO' },
  { name: 'Dr. Ritu Sharma', role: 'FAICO, Aravind Eye Hospital', text: 'Topic-wise MCQs mapped exactly to the FAICO syllabus. Could not have passed without them.', exam: 'FAICO' },
];

/** FAQ items */
export const FAQS = [
  { q: 'What is OphthaMCQ?', a: "OphthaMCQ is the world's only ophthalmology PG exam notes and MCQ question bank — built by gold medalists and exam toppers who personally passed ICO, FAICO, DNB and FRCOphth. Trusted by 15,000+ ophthalmologists, PGs and residents across India and 23 countries." },
  { q: 'Which exams does OphthaMCQ cover?', a: 'OphthaMCQ covers ICO/FICO, FAICO, DNB/MS/DO and PDCET. FRCOphth resources coming soon.' },
  { q: 'Are the notes really handwritten?', a: 'Yes. Every page is handwritten by ophthalmologists who topped their MS, DNB and fellowship exams — distilled from Ryan, Kanski, Elkington, BCSC and Khurana into concise exam-ready bullet points.' },
  { q: 'Can I try before I buy?', a: 'Yes. Access free sample questions and notes on OphthaMCQ before purchasing anything. No credit card required.' },
  { q: 'Are ICO/FICO past papers available anywhere else?', a: 'No. OphthaMCQ is the world\u2019s first and only platform with complete ICO/FICO past papers and full explanations. Not available anywhere else on the planet.' },
  { q: 'How do I access my purchases?', a: 'After purchase you get instant PDF access plus lifetime access via the OphthaMCQ app on Android and iOS. Syncs across all devices.' },
  { q: 'How do I buy products?', a: 'Click any Buy Now button to go to our secure store on ophthamcq.com. Complete your purchase there and access your content instantly.' },
  { q: 'Is OphthaMCQ available outside India?', a: 'Yes. OphthaMCQ is used by ophthalmology PGs and residents in 23 countries worldwide. ICO/FICO resources are especially popular internationally.' },
  { q: 'Do you offer institutional pricing?', a: 'Yes. Residency programs and eye hospitals can get bulk licenses for their residents. Contact us for a custom quote.' },
  { q: 'How often is content updated?', a: 'Question banks and notes are updated regularly based on the latest exam patterns, textbook editions and syllabus changes.' },
];
